image: hashicorp/terraform:light

stages:
  - test
  - plan
  - apply

include:
  - template: Security/SAST-IaC.latest.gitlab-ci.yml

iac-sast:
  stage: test
  artifacts:
    reports:
      sast: gl-sast-report.json
  variables:
    SAST_IAC_PATH: "Multi-cloud_Infrastucture"

plan:
  stage: plan
  script:
    - cd Multi-cloud_Infrastucture
    - terraform init
    - terraform plan -out=tfplan
  artifacts:
    paths:
      - Multi-cloud_Infrastucture/tfplan

apply:
  stage: apply
  script:
    - cd Multi-cloud_Infrastucture
    - terraform init
    - terraform apply -auto-approve tfplan
  only:
    - main
  when: manual