image:
  name: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

stages:
  - test
  - plan
  - deploy

include:
  - template: Security/SAST-IaC.latest.gitlab-ci.yml

iac-sast:
  stage: test
  artifacts:
    reports:
      sast: gl-sast-report.json
  variables:
    SAST_IAC_PATH: "01_Infrastructure"

plan:
  stage: plan
  script:
    - cd 01_Infrastructure
    - terraform init
    - terraform plan -out=tfplan
  artifacts:
    paths:
      - 01_Infrastructure/tfplan

apply:
  stage: deploy     
  script:
    - cd 01_Infrastructure
    - terraform init
    - terraform apply -auto-approve tfplan
  dependencies:
    - plan
  when: manual       
  only:
    - main


destroy:
  stage: deploy      
  script:
    - cd 01_Infrastructure
    - terraform init
    - terraform destroy -auto-approve
  when: manual      
  only:
    - main